name: Deploy

on:
  workflow_run:
    workflows: ["Production CI"]
    branches: [main]
    types:
      - completed
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: cd myCargonaut && npm ci && npm run build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: myCargonaut
