name: Deploy

on:
  workflow_run:
    workflows: ["Node.js CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    defaults:
      run:
        working-directory: myCargonaut
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
