name: Development

on:
  push:
    branches-ignore: [main]
    
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: (cd myCargonaut && npm ci)
      - name: Run Tests
        run: (cd myCargonaut && npm run test:ci)
  
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: (cd myCargonaut && npm ci)
      - name: Run Linter
        run: (cd myCargonaut && npm run lint)
  
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: (cd myCargonaut && npm ci)
      - name: Run Build
        run: (cd myCargonaut && npm run build)
      
      
  

