name: Development

on:
  push:
    branches-ignore: [main]
    
jobs:
  build_test_and_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: (cd myCargonaut && npm ci)
      - name: Install Angular-CLI
        run: (cd myCargonaut && npm i -g @angular/cli)
      - name: Run Build
        run: (cd myCargonaut && npm run build)
      - name: Run Linter
        run: (cd myCargonaut && npm run lint)
      - name: Run Tests
        run: (cd myCargonaut && npm run test:ci)
