name: Development

on:
  push:
    branches-ignore: [main]
    
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
     # - name: Install Dependencies
     #   run: (cd myCargonaut && npm ci)
     # - name: Run Unit-Tests
     #   run: (cd myCargonaut && npm run test:ci)

  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
     # - name: Install Dependencies
     #   run: (cd myCargonaut && npm ci)
     # - name: Run Linter
     #   run: (cd myCargonaut && npm run lint)

  Build_and_E2E-Tests:
    runs-on: ubuntu-latest
    needs: [Unit-Tests, Linter]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: (cd myCargonaut && npm ci)
      - name: Run Build
        run: (cd myCargonaut && npm run build)
      - name: Install Firebase-Tools
        run:  (cd myCargonaut && npm install -g firebase-tools)
      - name: Just a test run Firebase emulator in ci
        run: (cd myCargonaut && firebase emulators:start)
      #- name: Run Cypress E2E-Tests
       # run: (cd myCargonaut && npm run cypress-run:ci)