name: Development

on:
  push:
    branches: [ dev ]

  pull_request:
    branches: [ main, dev ]

jobs:
  testing_and_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: (cd myCargonaut && npm ci)
      - run: (cd myCargonaut && npm i -g @angular/cli)
      - run: (cd myCargonaut && npm run lint)
      - run: (cd myCargonaut && npm run test:ci)
