name: Production CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: (cd myCargonaut && npm ci)
      - run: (cd myCargonaut && npm i -g @angular/cli)
      - run: (cd myCargonaut && npm run build)
      - run: (cd myCargonaut && npm run lint)
      - run: (cd myCargonaut && npm run test:ci)
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    environment: 
      name: Firebase_Deploy
      url: mycargonaut-2e064.web.app
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: myCargonaut
