name: Production

on:
  push:
    branches: [ main ]

jobs:
  test_and_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      #- run: (cd myCargonaut && npm ci)
      #- run: (cd myCargonaut && npm i -g @angular/cli)
      #- run: (cd myCargonaut && npm run lint)
      #- run: (cd myCargonaut && npm run test:ci)
  
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test_and_linter
    environment: 
      name: Firebase
      url: https://mycargonaut-2e064.web.app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: (cd myCargonaut && npm ci)
      - run: (cd myCargonaut && npm run build)
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: myCargonaut
